// <auto-generated>
// Generated by ConstantsClassCreator
// </auto-generated>
public static class AssetAddress{

	  public const string JPG_TETSUWO2 = "jpg_tetsuwo2";
	  public const string NOBI         = "nobi";
	  public const string SERVAL       = "serval";
}
