// <auto-generated>
// ConstantsClassCreator クラスによって生成されました。
// </auto-generated>
public static class AssetAddress{

	  public const string ASSETS_ASSET_BUNDLE_NOBI_PNG    = "Assets/AssetBundle/nobi.png";
	  public const string ASSETS_ASSET_BUNDLE_SERVAL_JPG  = "Assets/AssetBundle/serval.jpg";
	  public const string ASSETS_ASSET_BUNDLE_TETSUWO_JPG = "Assets/AssetBundle/tetsuwo.jpg";
	  public const string EDITOR_SCENE_LIST               = "EditorSceneList";
	  public const string RESOURCES                       = "Resources";

}
