// <auto-generated>
// ConstantsClassCreator クラスによって生成されました。
// </auto-generated>
public static class AssetAddress{

	  public const string NOBI     = "nobi";
	  public const string SERVAL   = "serval";
	  public const string TETSUWO2 = "tetsuwo2";

}
